name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Train model to generate model.pkl
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          pip install -r requirements.txt
          python train.py

      - name: Deploy to HuggingFace
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: make deploy HF=$HF
